<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pegawai_model extends CI_Model
{

    public $table = 'm_pegawai';
    public $id = 'idpeg';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idpeg', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tgllhr', $q);
	$this->db->or_like('tmplhr', $q);
	$this->db->or_like('kelamin', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('kdgolongan', $q);
	$this->db->or_like('kdpangkat', $q);
	$this->db->or_like('kdjabatan', $q);
	$this->db->or_like('kdstatus', $q);
	$this->db->or_like('kdbidang', $q);
	$this->db->or_like('tglkerja', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idpeg', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tgllhr', $q);
	$this->db->or_like('tmplhr', $q);
	$this->db->or_like('kelamin', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('kdgolongan', $q);
	$this->db->or_like('kdpangkat', $q);
	$this->db->or_like('kdjabatan', $q);
	$this->db->or_like('kdstatus', $q);
	$this->db->or_like('kdbidang', $q);
	$this->db->or_like('tglkerja', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_pegawai_model.php */
/* Location: ./application/models/M_pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-15 12:02:04 */
/* http://harviacode.com */